### ISSUE TITLE
Multilevel lookup on Windows

### ISSUE THREAD

**Issue by clairernovotny** [actions/setup-dotnet#10]
Please see the Azure Pipelines task:
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts

There needs to be control over how .NET Core is located

**Comment by damccorm** [comment]
Could you provide a little more context on why this is needed? From what I can tell, this only really matters when private runners are introduced (as of now we only have a hosted service, though private runners are coming) - is that right?

**Comment by onovotny** [comment]
It would be needed even on the hosted agents. Presumably there's some version of .NET Core installed on the host already, as it would be part of the base set of workloads. If a newer/other version is installed via this tool, then it applies.

**Comment by damccorm** [comment]
My instinct is to not do this, but I'm not 100% sure I understand the use case where this is needed. As I understand it though, all this is doing in the file you linked to is setting the `DOTNET_MULTILEVEL_LOOKUP` variable - that feels like it should just be a `run: set DOTNET_MULTILEVEL_LOOKUP=1` in the users' workflow in the cases where its needed, especially since my understanding is that this isn't the main use case.

I'm hesitant to add an extra option for this since it just seems like a configuration detail to me, but open to further conversation on why this is needed.

**Comment by onovotny** [comment]
I believe this is incorrect. People expect multi-level lookup to work since it is the default on Windows. No one even really knows that the `DOTNET_MULTILEVEL_LOOKUP` exists outside of the .NET Core team. 

People tend to install .NET Core and have it "just work."

In particular, this can break .NET Core global tools that don't have the rollForward attribute set. They happen to work just fine now because every release version of .NET Core is installed in the global location. 

Now someone installs a preview of .NET Core 3 but tries to run a .NET Core 2.1 global tool....without that attribute, or multi level lookup, it won't run.

**Comment by onovotny** [comment]
The default for that variable appears to be true on Windows...so setting it explicitly may not be needed unless to disable it (which I believe is uncommon). https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet?tabs=netcore21#environment-variables

**Comment by damccorm** [comment]
I guess my point is that we should follow the Windows default (which as you've pointed out is on in this case, so it should "just work"), rather than trying to enforce our own default. In the cases where it needs to be changed for some reason, there exists a simple way to do it on the command line, which doesn't really seem significantly more burdensome.

Note that in the cases where it needs to be set for the whole job, the user can do `run: ##[set-env name=DOTNET_MULTILEVEL_LOOKUP]0`

**Comment by onovotny** [comment]
Agreed. I was getting confused between the interaction of global tools an locally installed sdk's. It's not something most people have to think about since the environment defaults just work.

**Comment by damccorm** [comment]
Cool, thanks for working with me on this 😃. In that case I'm going to close here, comment if I should reopen.

**Comment by onovotny** [comment]
I'm not so sure this should be closed anymore.

https://github.com/dotnet/reactive/commit/35f512732da63bc63c5e6601b37f57ccbedfe6de

In that case, multiLevelLookup had to be true to enable it to use the global locations in addition to the one the tool installed. I don't think that's a good default.

**Comment by damccorm** [comment]
I think my instinct is still to use the Window's default here - I think I would need a more systematic set of reasoning to change away from what they're doing since they presumably know more about this than we do, even if one case does require the non-default option.

I guess what I'm asking is what makes the CI case different enough from the general case that we should have a different default?

**Comment by onovotny** [comment]
Something changed from the earlier version of the task to the latest ones in a breaking way. The earlier ones were additive to the ones already on the box.

That is, you install 3.x preview, and you could run 2.1 tests since 2.1 SDK's/runtimes were already there.

The later versions seem to prevent this from working without setting the flag. That seems counter-intuitive since users would not expect to have to re-install what's already on the image. 

I believe there should be a proper discussion with the .NET Team on this.

**Comment by onovotny** [comment]
(in the general case, they're on the box in the global location and just work). CI changes this by not using the global location.

**Comment by rainersigwald** [comment]
paging @kathleendollard

**Comment by damccorm** [comment]
Reopening for continued discussion

**Comment by ZEisinger** [comment]
Closing this stale issue. We have updated docs to raise awareness to the flag. Feel free to continue the discussion if appropriate.
