### ISSUE TITLE
.NET Framework Support wanted

### ISSUE THREAD

**Issue by MaledongGit** [actions/setup-dotnet#218]
**Description:**
There're still many "old" .net framework projects on GitHub by C#, and we also want a CI like .net core.  These .net framework are also supported on the list.

For more, you can see:  https://dotnet.microsoft.com/download/dotnet-framework

Would Microsoft consider publishing such a action package installer for windows platform ONLY with a bash/powershell file?

**Comment by vsafonkin** [comment]
Hi @MaledongGit, .NET Framework supports backward compatibility: NET Framework 4.8 can be used to run applications built for the .NET Framework 4.0 through 4.7.2 and version 4.8 is installed on Windows runner, so I'm not sure if there is a need to create a special action to install a specific version .NET Framework. As for version 3.5, we have not received requests from customers to install this version on Windows runner, so, most likely this action will not be in demand.

**Comment by MaledongGit** [comment]
@vsafonkin : Thanks, so you mean I can directly use 'MSBuild' command to build the app for GitHub CI? Any scripts or shells needed?

**Comment by xt0rted** [comment]
I've been using actions to build full framework projects ever since Windows support was released. I use [Cake](https://cakebuild.net/) to call MSBuild, but there's never been an issue getting it to work and nothing extra to setup/install. To call MSBuild directly you might need to use [microsoft/setup-msbuild](https://github.com/microsoft/setup-msbuild) or do some setup of your own with [vswhere](https://github.com/microsoft/vswhere) (my batch files/powershell scripts all used this already) but you shouldn't have to install any extra frameworks.

**Comment by MaledongGit** [comment]
@xt0rted : Thanks for your GREAT help, I'll take a look first

**Comment by vsafonkin** [comment]
Hi @MaledongGit, this issue still actual for you?

**Comment by vsafonkin** [comment]
Closed, because the issue is not actual.
