### ISSUE TITLE
Write resolved sdk version to output variable

### ISSUE THREAD

**Issue by MeikTranel** [actions/setup-dotnet#241]
**Description:**
Once an SDK version is installed the action should set an output variable where one can read the version installed for reuse.

**Justification:**
Workspaces with global.json can skip providing a version to the setup-dotnet action. But when you write more complex workflows with multiple jobs you dont always want to checkout the repository to have that `global.json` available. I'd like to have a resolved version available once the setup has been run during an initial build job.

**Are you willing to submit a PR?**

Sure - Should be a simple addition to the action.yml and two lines in index.js 😂

**Comment by vsafonkin** [comment]
Hi @MeikTranel, in case of multiple jobs you should pass the value of this output variable to every job because every job is running on new runner. From my point of view, there is no advantage between getting version from some output variable instead `global.json` file and if the `global.json` file is available in initial build job, it should be available in other jobs. With using additional variable implicit logic arises for getting version. I would rather not make such changes. Please, correct me if I misunderstood something.

**Comment by IvanZosimov** [comment]
Hi, @MeikTranel 👋  The functionality you asked for was implemented in the new [`v3`](https://github.com/actions/setup-dotnet/tree/v3) version of `setup-dotnet` action. By now I'm going to close this issue, If you have any additions or questions feel free to ping us.
